openapi: 3.0.1
info:
  title: helloService
  description: ''
  version: '1.0'
servers:
  - url: https://apiops-apim-dev.azure-api.net/helloService
paths:
  /:
    post:
      summary: hello
      description: hello
      operationId: hello
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]